server:
  port: ":8080"
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60

database:
  mysql:
    dsn: "root:123456@tcp(localhost:3306)/url_shortener?charset=utf8mb4&parseTime=True&loc=Local"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 300

redis:
  addr: "localhost:6379"
  password: ""
  db: 0